### ISSUE TITLE
"First" player in server doesn't share Stars

### ISSUE THREAD

**Issue by JustAnotherRandomLad** [net64-mod/net64-mod.github.io#19]
When I host a private server using Net64 v2.3 (server setup window indicates that part is v2.2.2) to play with friends, it seems there's always one player such that when they collect a Star, the other players don't receive it. (This player still receives any Stars collected by others.) I tested this with different hosts and different player-joining orders, and it seems that the "one player" is always whoever is at the top left of the player list for the server (usually the first to join, but it changes if that player leaves and rejoins).

**Comment by SeanRaider** [comment]
Exact same issue my friend and I were having. I was going insane. I've heard a lot of people are having issues with the integrated one touch server hosting, and are having better luck just using the separate server software and connecting manually to their own server with 127.0.0.1. Hopefully they fix the integrated one soon because it's a really nice idea.

**Comment by Tarnadas** [comment]
Is this a problem with the 2.2 server software or with the integrated one?
I would be wondering, if there is a difference between starting 2.2 externally or from within the client, because it's the exact same software

**Comment by JustAnotherRandomLad** [comment]
This only happens when the server is hosted from within the client. Using the separate server software (as with 2.1) doesn't result in this problem.

**Comment by JustAnotherRandomLad** [comment]
This only happens when the server is used from within the client. Starting the v2.2 server software externally doesn't result in this issue.

Also, the affected player can't be seen by others, although said player can still see everyone else, and the others can all see each other.

**Comment by JustAnotherRandomLad** [comment]
I just tested v2.2.3, and it still has this issue.
